"""
Rertieve aborted jobs and show reason for abort in case of error
"""
import sys
import argparse
# from pathlib import Path
import defusedxml.minidom
import requests

PRINTERURL="http://PRISMAsync.cpp.canon:8010"

JMFSTATUS = """MIME-Version: 1.0
Content-Type: multipart/related; boundary="I_Love_PRISMAsync"

--I_Love_PRISMAsync
Content-ID: part1@cpp.canon
Content-Type: application/vnd.cip4-jmf+xml
content-transfer-encoding:7bit 
Content-Disposition: attachment

<JMF xmlns="http://www.CIP4.org/JDFSchema_1_1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.CIP4.org/JDFSchema_1_1 http://schema.cip4.org/jdfschema_1_3/JDF.xsd" MaxVersion="1.3" SenderID="CIP4 Alces 2.3" TimeStamp="2015-11-27T17:01:04+01:00" Version="1.3" xsi:type="JMFRootMessage">
  <!-- Generated by the CIP4 Java open source JDF Library version : CIP4 JDF Writer Java 1.5 BLD 79 -->
  <Query ID="ALCES_E5QLNT_113_20151127170104" Type="QueueStatus" xsi:type="QueryQueueStatus">
    <QueueFilter MaxEntries="500" QueueEntryDetails="JDF" StatusList="Aborted">
          <QueueEntryDef QueueEntryID="REPLACEXXX"/>
    </QueueFilter>
  </Query>
</JMF>

--I_Love_PRISMAsync--"""
JMFQUERY="""MIME-Version: 1.0
Content-Type: multipart/related; boundary="I_Love_PRISMAsync"

--I_Love_PRISMAsync
Content-ID: part1@cpp.canon
Content-Type: application/vnd.cip4-jmf+xml
content-transfer-encoding:7bit 
Content-Disposition: attachment

<JMF xmlns="http://www.CIP4.org/JDFSchema_1_1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" MaxVersion="1.3" SenderID="Python by hdok" TimeStamp="2020-08-30T11:39:00+02:00" Version="1.3" xsi:type="JMFRootMessage">
      <Query ID="Completed-12345" Type="QueueStatus" xsi:type="QueryQueueStatus">
        <QueueFilter StatusList="STATUS"/>
    </Query>
</JMF>

--I_Love_PRISMAsync--"""


def ReturnQueueEntries (s_url, status):
  """Return all queue entries with the given states

    Parameters:
    url: full link to printer jmf interface e.g. http://prismasync.lan:8010
    status: states that need to be reported (e.g. "Completed Aborted") use " " to not filter at all and receive all queue entries

    Returns:
    array of QueueEntryIDs

  """
  # Create a jmf message to retrieve the queue status that Filters on job status, it is allowed to mention multiple job statuses
  data=JMFQUERY.replace("STATUS",status)
  s_headers={'Content-Type': 'multipart/related'}

  try:
    s_response=requests.post(url=s_url,data=data,headers=s_headers)
    s_root = defusedxml.minidom.parseString(s_response.content)
  except (requests.exceptions.ConnectionError, requests.exceptions.ConnectTimeout):
    print("Unexpected reply from", url)
    print(sys.exc_info()[0], "occurred.")
    s_id_array=[]
    return s_id_array
  Entries=s_root.getElementsByTagName("QueueEntry")
  s_id_array=[]
  for qid in Entries:
    s_id_array.append(qid.getAttribute("QueueEntryID"))
  return s_id_array


# The following block is used to take command line options for this tool.
parser = argparse.ArgumentParser(description='Retrieve aborted jobs and show Abort reason')

parser.add_argument('--url', type=str, default=PRINTERURL,
                    help='full url to PRISMAsync jmf interface. (default: '+PRINTERURL+')')
args = parser.parse_args()
url=args.url
namespaces = {'jdf': 'http://www.CIP4.org/JDFSchema_1_1'}
qeid=ReturnQueueEntries(url, "Aborted")
for i in qeid:
  message=JMFSTATUS.replace("REPLACEXXX", str(i))
  headers={'Content-Type': 'multipart/related'}
  print("#### QueueEntryId:",i,"####")
  # Create a jmf message to retrieve the queue status that Filters on job status, it is allowed to mention multiple job statuses
  try:
    response=requests.post(url=url,data=message,headers=headers)
    root = defusedxml.minidom.parseString(response.content)
  except (requests.exceptions.ConnectionError, requests.exceptions.ConnectTimeout):
    print("Unexpected reply from", url)
    print(sys.exc_info()[0], "occurred.")
    exit()
  DescriptiveName=root.getElementsByTagName("JDF")[0].getAttribute("DescriptiveName")
  print(" DescriptiveName=",DescriptiveName)

  id_array=[]
  AuditPools=root.getElementsByTagName("AuditPool")
  print(" StatusDetails=",root.getElementsByTagName("JDF")[0].getAttribute("StatusDetails"))

  for ap in AuditPools:
    Notifications=ap.getElementsByTagName("Notification")
    if Notifications:
      for no in Notifications:
        Comments=no.getElementsByTagName("Comment")
        for co in Comments:
          print("", co.firstChild.nodeValue)
    # id_array.append(qid.getAttribute("QueueEntryID"))
  