#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
SetupConfig creates and populates a .config folder with default files
for JMF tools: SubmitQueueEntry.jmf, Template.jdf, and Test.pdf
"""
import sys
from pathlib import Path
from CreateTestPDF import create_test_pdf


def get_tools_dir():
    """Get the directory containing this tool, handling both script and PyInstaller execution."""
    # For PyInstaller executables, sys.argv[0] points to the actual exe location
    script_path = Path(sys.argv[0]).resolve()
    if script_path.is_file() and script_path.exists():
        return script_path.parent
    # For script execution, use __file__
    return Path(__file__).resolve().parent


# Default SubmitQueueEntry.jmf content
SUBMIT_JMF_CONTENT = """<JMF TimeStamp="2020-06-19T12:09:38-07:00" Version="1.4" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://www.CIP4.org/JDFSchema_1_1">
    <Command ID="Submit-Job-PRISMAsync" Type="SubmitQueueEntry">
        <QueueSubmissionParams URL="REPLACE_URL">
            <QueueFilter QueueEntryDetails="None" MaxEntries="1" >
            </QueueFilter>
        </QueueSubmissionParams>
    </Command>
</JMF>
"""

# Default Template.jdf content
TEMPLATE_JDF_CONTENT = """<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<JDF xmlns="http://www.CIP4.org/JDFSchema_1_1" Activation="Active" Category="DigitalPrinting" ID="REPLACE_ID" JobID="REPLACE_JOBID" JobPartID="REPLACE_JOBPARTID" Status="Waiting" Type="Combined" Types="LayoutPreparation Imposition Interpreting Rendering ColorCorrection Folding DigitalPrinting HoleMaking Gathering Screening ColorSpaceConversion Stitching oce:Mailbox" Version="1.3" xmlns:oce="http://www.oce.com/JDF_Extension/1_00" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:type="Combined">
    <!--Generated by the CIP4 C++ open source JDF Library version  -->
    <Comment ID="c190712202412.-001_000034" Name="oce:TicketVersion">4.00</Comment>
    <Comment ID="c190712202412.-001_000035" Name="oce:DocumentDimension">612.000 792.000</Comment>
    <ResourcePool>
        <CustomerInfo Class="Parameter" ID="r190712202412.-001_000036" Status="Available">
            <Company OrganizationName="RedGrendel Production Printing" />
        </CustomerInfo>
        
        <Contact ContactTypes="Customer" Class="Parameter" ID="r190712202412.-001_000037" Status="Available"/>
        <LayoutElement Class="Parameter" ID="r190712202412.-001_000038" Status="Available">
            <FileSpec URL="http://test/" />
        </LayoutElement>
        <RunList Class="Parameter" ID="r190712202412.-001_000039" Status="Available">
            <LayoutElementRef rRef="r190712202412.-001_000038" />
        </RunList>
        <Media Class="Consumable" DescriptiveName="Bulk 90gr" Dimension="841.88976378 1190.5511811" HoleType="None" ID="r190712202412.-001_000040" MediaColorName="White" MediaSetCount="1" Status="Available" Weight="90" oce:CustomMediaType="Color Copy" />
        <LayoutPreparationParams Class="Parameter" ID="r190712202412.-001_000041" Rotate="Rotate0" Sides="TwoSidedFlipY" Status="Available">
            <FitPolicy SizePolicy="ClipToMaxPage" />
            <PageCell>
                <ImageShift PositionX="Center" PositionY="Center" ShiftBack="0 0" ShiftFront="0 0" />
            </PageCell>
        </LayoutPreparationParams>
        <InterpretingParams Class="Parameter" ID="r190712202412.-001_000042" Scaling="1 1" Status="Available" oce:MinLineWidthAdjustment="Off" />
        <RenderingParams Class="Parameter" ID="r190712202412.-001_000043" Status="Available" oce:LineTextFatteningAdjustment="Off">
            <ObjectResolution Resolution="600 600" />
        </RenderingParams>
        <ColorCorrectionParams Class="Parameter" ID="r190712202412.-001_000044" Status="Available">
            <ColorCorrectionOp AdjustContrast="0" AdjustLightness="0" />
        </ColorCorrectionParams>
        <ColorSpaceConversionParams Class="Parameter" ID="r190712202412.-001_000045" Status="Available">
            <GeneralID IDUsage="oce:EnhancedColorRendering" IDValue="Off" />
        </ColorSpaceConversionParams>
        <ScreeningParams Class="Parameter" ID="r190712202412.-001_000046" Status="Incomplete" />
        <DigitalPrintingParams Class="Parameter" Collate="Sheet" ID="r190712202412.-001_000047" OutputBin="AutoSelect" Status="Available">
            <Disjointing OffsetDirection="None" />
            <MediaRef rRef="r190712202412.-001_000040" />
        </DigitalPrintingParams>
        <Component Class="Quantity" ComponentType="PartialProduct" ID="r190712202412.-001_000048" Status="Unavailable" />
        <oce:MailboxDetails Class="Parameter" ID="r190712202412.-001_000049" Status="Available" UseMailbox="false" />
        <HoleMakingParams HoleType="R4-generic" Class="Parameter" ID="r190712202412.-001_000050" Status="Available" NoOp="true"/>
        <FoldingParams Class="Parameter" ID="r190712202412.-001_000051" NoOp="true" Status="Available" />
        <StitchingParams Class="Parameter" ID="r190712202412.-001_000052" NumberOfStitches="0" Status="Available" StitchType="Side" />
        <Component Class="Quantity" ComponentType="PartialProduct" ID="r190712202412.-001_000053" Status="Unavailable" />
        <Component Class="Quantity" ComponentType="PartialProduct" ID="r190712202412.-001_000054" Status="Unavailable" />
        <Component Class="Quantity" ComponentType="FinalProduct" DescriptiveName="Final Component" ID="r190712202412.-001_000055" Status="Unavailable" />
        <UsageCounter Class="Consumable" Scope="Job" Status="Available" CounterTypes="Impressions" ID="UsageCounter_ID" />
    </ResourcePool>
    <ResourceLinkPool>
        <CustomerInfoLink Usage="Input" rRef="r190712202412.-001_000036" />
        <ContactLink Usage="Input" rRef="r190712202412.-001_000037" />
        <LayoutElementLink Usage="Input" rRef="r190712202412.-001_000038" />
        <RunListLink Usage="Input" rRef="r190712202412.-001_000039" />
        <MediaLink Usage="Input" rRef="r190712202412.-001_000040" />
        <LayoutPreparationParamsLink Usage="Input" rRef="r190712202412.-001_000041" />
        <InterpretingParamsLink Usage="Input" rRef="r190712202412.-001_000042" />
        <RenderingParamsLink Usage="Input" rRef="r190712202412.-001_000043" />
        <ColorCorrectionParamsLink Usage="Input" rRef="r190712202412.-001_000044" />
        <ColorSpaceConversionParamsLink Usage="Input" rRef="r190712202412.-001_000045" />
        <ScreeningParamsLink Usage="Input" rRef="r190712202412.-001_000046" />
        <DigitalPrintingParamsLink Usage="Input" rRef="r190712202412.-001_000047" />
        <ComponentLink CombinedProcessIndex="6" Usage="Output" rRef="r190712202412.-001_000048" />
        <oce:MailboxDetailsLink Usage="Input" rRef="r190712202412.-001_000049" />
        <HoleMakingParamsLink Usage="Input" rRef="r190712202412.-001_000050" />
        <FoldingParamsLink Usage="Input" rRef="r190712202412.-001_000051" />
        <StitchingParamsLink Usage="Input" rRef="r190712202412.-001_000052" />
        <ComponentLink CombinedProcessIndex="11" Orientation="Flip0" Usage="Input" rRef="r190712202412.-001_000053" />
        <ComponentLink CombinedProcessIndex="11" Orientation="Flip0" Usage="Output" rRef="r190712202412.-001_000054" />
        <ComponentLink Amount="1" Usage="Output" rRef="r190712202412.-001_000055" />
    </ResourceLinkPool>
</JDF>
"""


def confirm_overwrite(file_path):
    """Ask user for confirmation before overwriting a file."""
    if file_path.exists():
        while True:
            response = input(f"File exists: {file_path.name}. Overwrite? (y/n): ").strip().lower()
            if response in ('y', 'yes'):
                return True
            elif response in ('n', 'no'):
                return False
    return True


def setup_config():
    """Create and populate .config folder with default files."""
    # Create .config in the tools directory
    tools_dir = get_tools_dir()
    config_dir = tools_dir / '.config'
    
    # Create .config directory
    config_dir.mkdir(exist_ok=True)
    print(f"✅ Created/verified .config directory: {config_dir}\n")
    
    # Write SubmitQueueEntry.jmf
    jmf_target = config_dir / 'SubmitQueueEntry.jmf'
    if confirm_overwrite(jmf_target):
        try:
            with open(jmf_target, 'w') as f:
                f.write(SUBMIT_JMF_CONTENT)
            print(f"✅ Created SubmitQueueEntry.jmf")
        except Exception as e:
            print(f"❌ Failed to create SubmitQueueEntry.jmf: {e}")
    else:
        print(f"⏭️  Skipped SubmitQueueEntry.jmf")
    
    # Write Template.jdf
    jdf_target = config_dir / 'Template.jdf'
    if confirm_overwrite(jdf_target):
        try:
            with open(jdf_target, 'w') as f:
                f.write(TEMPLATE_JDF_CONTENT)
            print(f"✅ Created Template.jdf")
        except Exception as e:
            print(f"❌ Failed to create Template.jdf: {e}")
    else:
        print(f"⏭️  Skipped Template.jdf")
    
    # Create Test.pdf
    pdf_target = config_dir / 'Test.pdf'
    if confirm_overwrite(pdf_target):
        try:
            print(f"\nCreating Test.pdf...")
            create_test_pdf(
                pdf_target,
                num_pages=1,
                title="Test PDF for JMF",
                text="This is a test PDF created by SetupConfig for use with JMF tools."
            )
        except Exception as e:
            print(f"❌ Failed to create Test.pdf: {e}")
    else:
        print(f"⏭️  Skipped Test.pdf")
    
    print(f"\n{'='*60}")
    print(f"✅ Setup complete!")
    print(f"Config folder: {config_dir}")
    print(f"{'='*60}")


if __name__ == '__main__':
    setup_config()
